Reci-Me.UI/Controllers/ContactUsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Reci_me.BL;
using Reci_Me.UI.ViewModels;

namespace Reci_Me.UI.Controllers
{
    public class ContactUsController : Controller
    {
        // GET: ContactUsController
        public ActionResult Index()
        {
            UserVM userVM = new UserVM();
            userVM.User = UserManager.LoadContact()[0];
            return View(userVM);
        }

        // GET: ContactUsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ContactUsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ContactUsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ContactUsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ContactUsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ContactUsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ContactUsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Reci-Me.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Reci_Me.UI.Models;
using System.Diagnostics;

namespace Reci_Me.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        // GET: HomeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HomeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: HomeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: HomeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Reci-Me.UI/Controllers/RecipeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Reci_me.BL;
using Reci_me.BL.Models;
using Reci_Me.UI.ViewModels;

namespace Reci_Me.UI.Controllers
{
    public class RecipeController : Controller
    {
        private readonly IWebHostEnvironment _host;

        public RecipeController(IWebHostEnvironment host)
        {
            // Store the parameter from the constructor into a private, readonly field
            _host = host;
        }

        // LOADS
        // GET: RecipeController
        public ActionResult Index()
        {
            ViewBag.Title = "Recipes";
            return View(RecipeManager.Load());
        }

        // GET: RecipeController/Details/5
        /*public ActionResult Details()
        {
            //Recipe recipe = RecipeManager.LoadById(id);
            return View();
        }*/
        public ActionResult Details(Guid id)
        {
            Recipe recipe = RecipeManager.LoadById(id);
            return View(recipe);
        }

        public ActionResult DetailsName(String name)
        {
            Recipe recipe = RecipeManager.LoadByName(name);
            return View("Details",recipe);
        }

        public ActionResult Browse(Guid id)
        {
            ViewBag.Title = "Recipes";
            return View(nameof(Index), RecipeManager.Load(id));
        }


        // CREATES
        // GET: RecipeController/Create
        public ActionResult Create()
        {
            ViewBag.Title = "Create a Recipe";
            RecipeVM recipeVM = new RecipeVM();
            return View(recipeVM);
        }

        // POST: SubmitRecipeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RecipeVM recipeVM)
        {
            try
            {
                if(recipeVM.File != null)
                {
                    recipeVM.Recipe.MainImagePath = recipeVM.File.FileName;
                    // Upload the File
                    string path = _host.WebRootPath + "\\images\\Recipe\\";
                    if (!System.IO.File.Exists(path + recipeVM.File.FileName))
                    {
                        using (var stream = System.IO.File.Create(path + recipeVM.File.FileName))
                        {
                            recipeVM.File.CopyTo(stream); // upload the code to the server
                            ViewBag.Message = "File uploaded successfully";
                        }
                    }
                }

                recipeVM.Recipe.Id = Guid.NewGuid();
                RecipeManager.Insert(recipeVM.Recipe);


                int instructionNum = 1;
                foreach(Instruction i in recipeVM.Recipe.Instructions)
                {
                    if (i.Text == "ignore" || i.Text == null) break;
                    i.Id = Guid.NewGuid();
                    i.RecipeId = recipeVM.Recipe.Id;
                    i.InstructionNum = instructionNum;
                    RecipeInstructionManager.Insert(i);
                    instructionNum++;
                }

                for (int i = 0; i < recipeVM.Recipe.Ingredients.Count; i++)
                {
                    if (recipeVM.MeasuringTypes[i] != null)
                    {
                        RecipeIngredient recIng = new RecipeIngredient
                        {
                            Id = Guid.NewGuid(),
                            RecipeId = recipeVM.Recipe.Id,
                            IngredientId = recipeVM.Ingredients[i].Id,
                            MeasuringId = recipeVM.MeasuringTypes[i].Id,
                            Quantity = 1,
                            IsOptional = false,
                        };
                        RecipeIngredientManager.Insert(recIng);
                    }
                }

                //Instruction testInstruction = new Instruction
                //{
                //    Id = new Guid(),
                //    Text = "test upload",
                //    InstructionNum = 1,
                //    RecipeId = recipeVM.Recipe.Id
                //};
                //RecipeInstructionManager.Insert(instruction);

                //RecipeIngredient testIngredient = new RecipeIngredient
                //{
                //    Id = Guid.NewGuid(),
                //    RecipeId = recipeVM.Recipe.Id,
                //};
                //RecipeIngredientManager.Insert(testIngredient);

                return RedirectToAction(nameof(Index), "Home");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.Title = "Error";
                return View(recipeVM);
            }
        }


        // EDITS
        // GET: RecipeController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RecipeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        // DELETES
        // GET: RecipeController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RecipeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Reci-Me.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&family=Permanent+Marker&family=Satisfy&display=swap" rel="stylesheet">
</head>

<body>  
    <div>
        <h1 id="header" style="text-align: center; font-family: 'Libre Baskerville', serif;">
            Recipe of the day:
            <a id="lnkText" class="text-dark text-decoration-none" asp-area="" asp-controller="Recipe" asp-action="DetailsName" asp-route-name="Steak on the Stovetop"></a>
    </h1>     
    </div>
</body>
<body onload="RecipeDaily()">
    <div class="wrapper mt-4" style="width:100%; text-align:center; max-width:1200px">
        <div class="hero-text">
            <h1 id="randText"><mark>Recipe of the week: Buffalo Wings</mark></h1>
        </div>
        <div class="hero-image">
            <img id="randImg" class="img-fluid" src="~/css/img/wings.jpg" height="350" width="350" style="border-radius: 15px; max-height: 250px; max-width: 250px;" />
        </div>
        @*<div>
        For an eventual brief description of the dish
        <p id="desc"></p>
        </div>*@
        <div class="hero-text">
            <br />
        </div>
    </div>
    <script src="~/js/recipeOfTheDay.js">
    </script>
</body>
<br />
<br />
<div class="card" style="padding: 10px; font-family: 'Libre Baskerville', serif;">
    <p>Reci-Me is a popular recipe website that offers users a seamless platform to search, save and create delicious recipes. With a vast collection of recipes from around the world, users can easily search for recipes based on their dietary preferences, ingredients, cooking methods, and more. The website's user-friendly interface allows users to create personalized recipe collections and easily access them from any device. Additionally, Reci-Me enables users to create and share their own unique recipes, making it an excellent platform for passionate cooks and aspiring chefs. With its extensive recipe database and interactive features, Reci-Me is a must-visit website for anyone looking to enhance their culinary skills and explore new flavors.   -- <em>Your RECI-ME Team</em></p>
</div>
<br />
<br />
<div class="card container-fluid">
    <div class="Taco Gallery">
        <h3 style="text-align:center; font-family: 'Libre Baskerville', serif;">Surround yourself with tacos, not negativity.</h3>
        </div>
    <div class="row">
        <div class="col-xs-12 col-md-3">
            <img src="css/img/BreakfastTacos.png" height="250" width="250" class="img-responsive" />
        </div>
        <div class="col-xs-12 col-md-3">
            <img src="css/img/CaribbeanChickenTacos.png" height="250" width="250" class="img-responsive" />
        </div>
        <div class="col-xs-12 col-md-3">
            <img src="css/img/ChorizoTacos.png" height="250" width="250" class="img-responsive" />
        </div>
        <div class="col-xs-12 col-md-3">
            <img src="css/img/FlankSteakTacos.png" height="250" width="250" class="img-responsive" />
        </div>
        <div class="col-xs-12 col-md-3">
            <img src="css/img/RockFishTacos.png" height="250" width="250" class="img-responsive" />
        </div>
        <div class="col-xs-12 col-md-3">
            <img src="css/img/SweetPotatoBlackBeanTacos.png" height="250" width="250" class="img-responsive" />
        </div>
        <div class="col-xs-12 col-md-3">
            <img src="css/img/VeganBreakFastTacos.png" height="250" width="250" class="img-responsive" />
        </div>
        <div class="col-xs-12 col-md-3">
            <img src="css/img/JalapenoLimeSteakTacos.png" height="250" width="250" class="img-responsive" />
        </div>
    </div>
</div>
<br />
<br />
<div class="card" style="padding: 10px; font-family: 'Libre Baskerville', serif;">
    <p>The creators of Reci-Me come from diverse backgrounds, but they all share a passion for food and exploring different cuisines. Some have formal culinary training, while others have learned through travel and experimentation in the kitchen. They believe that food is a universal language that brings people together and allows them to experience different cultures and traditions. With this shared love of food, they have come together to create a platform where people can discover, learn and share their favorite recipes with others. Through their collective knowledge and expertise, they have built a website that offers a wide variety of recipes from all around the world, catering to different tastes and dietary needs. They hope that their website inspires others to discover and explore new foods and flavors, and to enjoy the many benefits of cooking and sharing meals with loved ones.</p>
</div>
<br />
<br />

    <div class="row">
    <h3 style="text-align:center; font-family: 'Libre Baskerville', serif;">Meet The Team</h3>
    <div class="column">
        <div class="card">
            <img src="css/img/Abigail.png" alt="Abigail" style="width:100%">
            <div class="container">
                <h2>Abigail</h2>
                <p class="title">Software Developer</p>
                <p>
                    <a asp-controller="ContactUs" asp-action="Index"><button class="button">Contact</button></a>
                </p>
            </div>
        </div>
    </div>

    <div class="column">
        <div class="card">
            <img src="css/img/Spencer.png" alt="Spencer" style="width:100%">
            <div class="container">
                <h2>Spencer</h2>
                <p class="title">Software Developer</p>
                <p>
                    <a asp-controller="ContactUs" asp-action="Index"><button class="button">Contact</button></a>
                </p>
            </div>
        </div>
    </div>

    <div class="column">
        <div class="card">
            <img src="css/img/Byron.png" alt="Byron" style="width:100%">
            <div class="container">
                <h2>Byron</h2>
                <p class="title">Software Developer</p>
                <p>
                    <a asp-controller="ContactUs" asp-action="Index"><button class="button">Contact</button></a>
                </p>
            </div>
        </div>
    </div>

    <div class="column">
        <div class="card">
            <img src="css/img/Max.png" alt="Max" style="width:100%">
            <div class="container">
                <h2>Max</h2>
                <p class="title">Software Developer</p>
                <p>
                    <a asp-controller="ContactUs" asp-action="Index"><button class="button">Contact</button></a>
                </p>
            </div>
        </div>
    </div>

    <div class="column">
        <div class="card">
            <img src="css/img/John.png" alt="John" style="width:100%">
            <div class="container">
                <h2>John</h2>
                <p class="title">Web Developer</p>
                <p>
                    <a asp-controller="ContactUs" asp-action="Index"><button class="button">Contact</button></a>
                </p>
            </div>
        </div>
    </div>
</div>